### ISSUE TITLE
Python 3 issues

### ISSUE THREAD

**Issue by Alexis-benoist** [davidvilla/pydot#4]
Hey,

I'm trying to port my module to python 3 and i have a problem to use it.
Here is the [travis report](https://travis-ci.org/Alexis-benoist/eralchemy/jobs/63250989).
The error is 
"""
data = ' graph {\n    graph [rankdir=LR];\n    node [label="\N",\n        shape=plaintext\n    ];\n    edge [color=gray50,\n...T></TD></TR></TABLE></FONT>>];\n"child" -- "parent" [taillabel=<<FONT>{0,1}</FONT>>,headlabel=<<FONT>0..N</FONT>>];\n}'
    def parse_dot_data(data):

```
    global top_graphs

    top_graphs = list()
```

> ```
>   if data.startswith(codecs.BOM_UTF8):
> ```
> 
> E       TypeError: startswith first arg must be str or a tuple of str, not bytes
> """
> Do you have any idea?

**Comment by johnyf** [comment]
`pydot >= 1.2.0` supports Python 3: https://github.com/erocarrera/pydot/issues/76.

**Comment by achaiah** [comment]
It looks like pydot-1.0.29 installation is broken again with pip and python 3.  I get:
```
Downloading pydot-1.0.29.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-qom6ktm8/pydot/setup.py", line 6, in <module>
        import pydot
      File "/tmp/pip-build-qom6ktm8/pydot/pydot.py", line 31
        except Exception, e:
                        ^
    SyntaxError: invalid syntax
```

**Comment by johnyf** [comment]
As I wrote [above](https://github.com/davidvilla/pydot/issues/4#issuecomment-253123222), `pydot >= 1.2.0` supports Python 3. Version 1.0.29 < 1.2.0. The latest version is [1.2.3](https://github.com/erocarrera/pydot/releases/tag/v1.2.3), and I would be surprised if it doesn't work with Python 3, because it is tested with Python 3.5. [on Tavis CI](https://github.com/erocarrera/pydot/blob/35a8d858bd9da0b37268fe9b317fe4895387e75f/.travis.yml#L6).

**Comment by achaiah** [comment]
OK thanks, I think I was confused by the release date of 1.0.29 on PyPI being listed as 2016-05-17 so I figured it was a newer release that should have been compatible with python3
